[package]
name = "oci"
version = "0.1.0"
edition = "2021"

[dependencies]
traits = { workspace = true }
oci-client = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
